[package]
name = "jjc"
version = "0.0.1"
description = "Reserved"
license = "MIT"
authors = ["jjc team"]
edition = "2018"

[lib]
name = "jjc"
path = "src/lib.rs"
test = false
bench = false

[dependencies]
rand = "0.7"